observer_mode=Observer Mode - Press escape to exit
formation_square=Formation: Square
formation_diamond=Formation: Diamond
formation_circle=Formation: Circle
formation_tight=Formation: Tight
formation_loose=Formation: Loose
formation_by_type=Formation: By Type
formation_default=Formation: Default
formation_star=Formation: Star
