new_game=New multiplayer game
skirmish=New single player game
standard_options=Standard options
advanced_options=Advanced options
game_name=Game name:
default_name={0}''s Game
rated_game=Rated game
rated_game_tip=Play for points (Requires {0} wins)
gamespeed=Game speed:
island_size=Island size:
terrain_type=Terrain type:
map_code=Map code:
min=Min
max=Max
hills=Hills:
trees=Trees:
resources=Resources:
human=Human
open=Open
closed=Closed
easy_ai=Easy AI
normal_ai=Normal AI
hard_ai=Hard AI
team=Team {0}
player=Player {0}:
players=Players:
enter_map_code=Enter map code...
min_name_length=Game name must be at least {0} characters.
min_num_teams=There must be at least {0} teams in the game.
large_unavailable=Large islands are unavailable in this demo version of Tribal Trouble.
hard_unavailable=Hard AI players are unavailable in this demo version of Tribal Trouble.
ai=AI
confirm_delete_preset=Delete preset "{0}"?
confirm_discard_changes=Discard your unsaved changes and load this preset?
max_chiefs_per_q=Max chiefs per quarters:
max_chiefs_total=Max total chiefs:
unlimited=Unlimited
initial_units=Initial units:
max_units=Max units:
max_buildings=Max buildings:
chief_heal_idle_seconds=Chieftain heal idle seconds:
chief_heal_amount=Chieftain heal amount:
target_quarters=Target quarters:
target_armories=Target armories:
max_concurrent_quarters=Max concurrent quarters:
max_concurrent_armories=Max concurrent armories:
num_resource_towers=Num resource towers:
max_concurrent_towers=Max concurrent towers:
