package com.oddlabs.tt.input;

public enum GameAction {
    // Global
    GLOBAL_QUIT,
    GLOBAL_TOGGLE_FULLSCREEN,
    GLOBAL_SCREENSHOT,
    GLOBAL_CHAT,
    GLOBAL_CHAT_TEAM,
    GLOBAL_MENU,
    GLOBAL_TOGGLE_STATUS,
    GLOBAL_AGGRESSIVE_UNITS,

    // Camera
    CAMERA_PAN_LEFT,
    CAMERA_PAN_RIGHT,
    CAMERA_PAN_UP,
    CAMERA_PAN_DOWN,
    CAMERA_PITCH_UP,
    CAMERA_PITCH_DOWN,
    CAMERA_ROTATE_LEFT,
    CAMERA_ROTATE_RIGHT,
    CAMERA_ZOOM_IN,
    CAMERA_ZOOM_OUT,
    CAMERA_MAP_MODE,
    CAMERA_FIRST_PERSON,
    CAMERA_ZOOM_MODE,

    // UI
    UI_ACTIVATE,
    UI_CANCEL,
    UI_FOCUS_NEXT,
    UI_FOCUS_PREV,
    UI_NEXT_PANEL,
    UI_PREV_PANEL,
    UI_NAV_UP,
    UI_NAV_DOWN,
    UI_NAV_LEFT,
    UI_NAV_RIGHT,
    UI_NAV_HOME,
    UI_NAV_END,
    UI_NAV_PAGE_UP,
    UI_NAV_PAGE_DOWN,
    UI_BACKSPACE,
    UI_DELETE,

    // Gameplay
    UNIT_MOVE,
    UNIT_ATTACK,
    UNIT_GATHER,
    UNIT_BUILD_QUARTERS,
    UNIT_BUILD_ARMORY,
    UNIT_BUILD_TOWER,
    UNIT_BUILD_SHIP,
    UNIT_EXIT_TOWER,
    UNIT_BEACON,
    UNIT_NEXT_IDLE,
    UNIT_SET_RALLY,
    GAMEPLAY_BACK,

    // Army Shortcuts
    ARMY_SELECT_0,
    ARMY_SELECT_1,
    ARMY_SELECT_2,
    ARMY_SELECT_3,
    ARMY_SELECT_4,
    ARMY_SELECT_5,
    ARMY_SELECT_6,
    ARMY_SELECT_7,
    ARMY_SELECT_8,
    ARMY_SELECT_9,

    ARMY_CREATE_0,
    ARMY_CREATE_1,
    ARMY_CREATE_2,
    ARMY_CREATE_3,
    ARMY_CREATE_4,
    ARMY_CREATE_5,
    ARMY_CREATE_6,
    ARMY_CREATE_7,
    ARMY_CREATE_8,
    ARMY_CREATE_9,

    // Production/Harvest (In Armory/Quarters submenus)
    PROD_WEAPONS,
    PROD_HARVEST,
    PROD_ARMY,
    PROD_TRANSPORT,

    // Resource Specific
    RES_TREE,
    RES_TREE_DEC,
    RES_TREE_BATCH,
    RES_TREE_BATCH_DEC,

    RES_ROCK,
    RES_ROCK_DEC,
    RES_ROCK_BATCH,
    RES_ROCK_BATCH_DEC,

    RES_IRON,
    RES_IRON_DEC,
    RES_IRON_BATCH,
    RES_IRON_BATCH_DEC,

    RES_CHICKEN,
    RES_CHICKEN_DEC,
    RES_CHICKEN_BATCH,
    RES_CHICKEN_BATCH_DEC,

    // Unit Specific
    TRAIN_PEON,
    TRAIN_PEON_DEC,
    TRAIN_PEON_BATCH,
    TRAIN_PEON_BATCH_DEC,

    TRAIN_CHIEFTAIN,

    // Magic
    MAGIC_1,
    MAGIC_2,
    MAGIC_3,//added by ikill240

    // Formations //added by ikill240c
    FORMATION_SQUARE, //added by ikill240c
    FORMATION_DIAMOND, //added by ikill240c
    FORMATION_CIRCLE, //added by ikill240c
    FORMATION_TIGHT, //added by ikill240c
    FORMATION_LOOSE, //added by ikill240c
    FORMATION_BY_TYPE, //added by ikill240c
    FORMATION_DEFAULT, //added by ikill240c
    FORMATION_STAR, //added by ikill240c

    // Unit stance commands //added by ikill240c
    STAND_GROUND, //added by ikill240c
    UNIT_GUARD, //added by ikill240c
    UNIT_PATROL, //added by ikill240c

    // Misc
    GAME_SPEED_UP,
    GAME_SPEED_DOWN,
    NOTIFICATION_JUMP,

    // Cheats
    CHEAT_1,
    CHEAT_2,
    CHEAT_3,
    CHEAT_4,
    CHEAT_5,
    CHEAT_6,
    CHEAT_7,
    CHEAT_8,
    CHEAT_9,

    DEBUG_PRINT_INFO,
    DEBUG_KILL_SELECTED,
    DEBUG_TOGGLE_LIGHT,
    DEBUG_TOGGLE_PLANTS,
    DEBUG_TOGGLE_PARTICLES,
    DEBUG_TOGGLE_AXES,
    DEBUG_TOGGLE_MISC,
    DEBUG_PROCESS_MISC,
    DEBUG_RESET_CURSOR,
    DEBUG_TOGGLE_DETAIL,
    DEBUG_CRASH,
    DEBUG_TOGGLE_FRAME_BUFFER,
    DEBUG_TOGGLE_BOUNDING,
    DEBUG_TOGGLE_FRUSTUM_FREEZE,
    DEBUG_FORCE_GC,
    DEBUG_START_RECORDING,
    DEBUG_TOGGLE_WATER,
    DEBUG_TOGGLE_AI,
    DEBUG_DUMP_ANIMATIONS
}
