package com.oddlabs.tt.model;

public enum DeployType {
    ROCK_WARRIOR,
    IRON_WARRIOR,
    RUBBER_WARRIOR,
    PEON,
    PEON_HARVEST_TREE,
    PEON_TRANSPORT_TREE,
    PEON_HARVEST_ROCK,
    PEON_TRANSPORT_ROCK,
    PEON_HARVEST_IRON,
    PEON_TRANSPORT_IRON,
    PEON_HARVEST_RUBBER,
    PEON_TRANSPORT_RUBBER
}
