error=Error
error_message=The game has crashed with the following message: "{0}".\n\
			  If this happened at startup, make sure you have updated drivers for your graphics card and sound card.
error_out_of_memory=The game ran out of memory. Try closing other applications, choosing a smaller map size, or increasing the memory limit the game is launched with.
error_custom_map=Couldn''t start the custom map game.\n\n{0}
